version: '3.7'
services:
  api-trein:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test