# production docker-compose file
version: '3.7'
services:
  api-trein:
    build:
      context: .
      dockerfile: Dockerfile.prod 
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - JWT_SECRET=${{ secrets.JWT_SECRET }}
  db:
    image: mysql:8.0.32
    container_name: db
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
      - MYSQL_DATABASE=${{ secrets.DATABASE_NAME }}
    volumes: 
    -  "./init.sql:/docker-entrypoint-initdb.d/1.sql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s