version: '3.7'
services:
  api-trein:
    build: .
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy 
  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes: 
    -  "./init.sql:/docker-entrypoint-initdb.d/1.sql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s