# production docker-compose file
version: '3.7'
volumes:
 rabbitmq_data: 
services:
  api-trein:
    image: ghcr.io/rodriguesrai/api-trein-nodejs-nestjs:latest
    ports:
      - 3000:3000
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      BATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      EC2_HOST: ${EC2_HOST}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      API_PORT: ${API_PORT}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-my
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest